version: '3'
services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo